name: .NET Agent All Solutions Build

# Does not run on PUSH since we have already ran all the test
on:
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]
  workflow_dispatch:

env:
  scripts_path: ${{ github.workspace }}\build\scripts
  tools_path: ${{ github.workspace }}\build\Tools
  DOTNET_NOLOGO: true

jobs:

  cancel-previous-workflow-runs:
    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # This builds both FullAgent and MSIInstaller since MSIInstaller requires FullAgent artifacts.
  build-test-fullagent-msi:
    name: Build and Test FullAgent and MSIInstaller
    runs-on: windows-2019

    env:
      fullagent_solution_path: ${{ github.workspace }}\FullAgent.sln
      msi_solution_path: ${{ github.workspace }}\src\Agent\MsiInstaller\MsiInstaller.sln

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.1

      - name: Setup VSTest Path
        uses: darenm/Setup-VSTest@v1
     
      - name: Install dependencies for FullAgent.sln
        run: |
          Write-Host ${{ env.tools_path }}\nuget.exe restore ${{ env.fullagent_solution_path }} -NoCache -Source `"https://www.nuget.org/api/v2`"
          ${{ env.tools_path }}\nuget.exe restore ${{ env.fullagent_solution_path }} -NoCache -Source "https://www.nuget.org/api/v2"
        shell: powershell

      - name: Install dependencies for MsiInstaller.sln
        run: |
          Write-Host ${{ env.tools_path }}\nuget.exe restore ${{ env.msi_solution_path }} -NoCache -Source `"https://www.nuget.org/api/v2`"
          ${{ env.tools_path }}\nuget.exe restore ${{ env.msi_solution_path }} -NoCache -Source "https://www.nuget.org/api/v2"
        shell: powershell
      
      - name: Build FullAgent.sln
        run: |
          Write-Host "MSBuild.exe -m -p:Configuration=Release -p:AllowUnsafeBlocks=true ${{ env.fullagent_solution_path }}"
          MSBuild.exe -m -p:Configuration=Release -p:AllowUnsafeBlocks=true ${{ env.fullagent_solution_path }}
        shell: powershell

      - name: Create agent_version.txt
        run: |
          $agentVersion = (Get-Item "${{ github.workspace }}\src\_build\AnyCPU-Release\NewRelic.Agent.Core\net45\NewRelic.Agent.Core.dll").VersionInfo.FileVersion
          Write-Host "Agent version $agentVersion"
          $agentVersion | Out-File -FilePath ${{ github.workspace }}\agent_version.txt -encoding utf8
        shell: powershell
        
      - name: Create agent_version.txt artifact
        uses: actions/upload-artifact@v2
        with:
          name: agent-version
          path: ${{ github.workspace }}\agent_version.txt
          if-no-files-found: error
      
      - name: Archive NewRelic.NuGetHelper
        uses: actions/upload-artifact@v2
        with:
          name: NewRelic.NuGetHelper
          path: ${{ github.workspace }}\build\NewRelic.NuGetHelper\bin
          if-no-files-found: error
          
      - name: Archive NewRelic.Agent.Extensions
        uses: actions/upload-artifact@v2
        with:
          name: NewRelic.Agent.Extensions
          path: ${{ github.workspace }}\src\Agent\NewRelic\Agent\Extensions\NewRelic.Agent.Extensions\bin\Release
          if-no-files-found: error

      - name: Archive FullAgent Home folders
        uses: actions/upload-artifact@v2
        with:
          name: homefolders
          path: |
            ${{ github.workspace }}\src\Agent\newrelichome_x64
            ${{ github.workspace }}\src\Agent\newrelichome_x64_coreclr
            ${{ github.workspace }}\src\Agent\newrelichome_x64_coreclr_linux
            ${{ github.workspace }}\src\Agent\newrelichome_x86
            ${{ github.workspace }}\src\Agent\newrelichome_x86_coreclr
          if-no-files-found: error

      - name: Get Code Signing Certificate
        id: write_cert
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'newrelic_code_sign_cert.pfx'
          encodedString: ${{ secrets.SIGNING_CERT }}
          
      - name: Install Code Signing Certificate
        run: |
          certutil.exe -f -user -p ${{ secrets.CERT_PASSPHRASE }} -importPFX ${{ steps.write_cert.outputs.filePath }} NoRoot
        shell: powershell

      - name: Build MsiInstaller.sln x86
        run: |
          Write-Host "MSBuild.exe -m -p:Configuration=Release -p:AllowUnsafeBlocks=true -p:Platform=x86 ${{ env.msi_solution_path }}"
          MSBuild.exe -m -p:Configuration=Release -p:AllowUnsafeBlocks=true -p:Platform=x86 ${{ env.msi_solution_path }}
        shell: powershell

      - name: Build MsiInstaller.sln x64
        run: |
          Write-Host "MSBuild.exe -m -p:Configuration=Release -p:AllowUnsafeBlocks=true -p:Platform=x64 ${{ env.msi_solution_path }}"
          MSBuild.exe -m -p:Configuration=Release -p:AllowUnsafeBlocks=true -p:Platform=x64 ${{ env.msi_solution_path }}
        shell: powershell

      - name: Archive _build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-folder-artifacts
          path: ${{ github.workspace }}\src\_build
          if-no-files-found: error

      - name: Archive NewRelic.OpenTracing.AmazonLambda.Tracer
        uses: actions/upload-artifact@v2
        with:
          name: NewRelic.OpenTracing.AmazonLambda.Tracer
          path: ${{ github.workspace }}\src\AwsLambda\AwsLambdaOpenTracer\bin\Release\netstandard2.0-ILRepacked
          if-no-files-found: error

  create-package-rpm:
    needs: build-test-fullagent-msi
    if: ${{ github.event.release }}
    name: Create RPM Package
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Download _build Artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-folder-artifacts
          path: src/_build

      - name: Download Agent Home Folders
        uses: actions/download-artifact@v2
        with:
          name: homefolders
          path: src/Agent
      
      - name: Download Agent Version
        uses: actions/download-artifact@v2
        with:
          name: agent-version
          path: ${{ github.workspace }}

      - name: Get GPG Key
        id: write_gpgkey
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'gpg.tar.bz2'
          encodedString: ${{ secrets.GPG_KEY }}

      - name: Copy GPG Key to keys
        run: |
          mkdir ${{ github.workspace }}/build/Linux/keys
          cp -f ${{ steps.write_gpgkey.outputs.filePath }} ${{ github.workspace }}/build/Linux/keys/gpg.tar.bz2
        shell: bash

      - name: Build RPM
        run: |
          sudo apt install dos2unix -y
          dos2unix ${{ github.workspace }}/agent_version.txt
          agentVersion=$(head -n 1 ${{ github.workspace }}/agent_version.txt)
          agentVersion=${agentVersion/$'\r\n\t'}
          cd ${{ github.workspace }}/build/Linux
          docker-compose build build_rpm
          docker-compose run -e AGENT_VERSION=$agentVersion -e GPG_KEYS=/keys/gpg.tar.bz2 build_rpm
        shell: bash
      
      - name: Archive Package Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-folder-artifacts
          path: ${{ github.workspace }}/src/_build
          if-no-files-found: error

  create-package-deb:
    needs: build-test-fullagent-msi
    if: ${{ github.event.release }}
    name: Create Debian package
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: Download Agent Home Folders
        uses: actions/download-artifact@v2
        with:
          name: homefolders
          path: src/Agent

      - name: Download _build Artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-folder-artifacts
          path: src/_build

      - name: Download agent_version.txt
        uses: actions/download-artifact@v2
        with:
          name: agent-version
          path: ${{ github.workspace }}

      - name: Build debian package
        run: |
          sudo apt install dos2unix -y
          dos2unix ${{ github.workspace }}/agent_version.txt
          agentVersion=$(head -n 1 ${{ github.workspace }}/agent_version.txt)
          agentVersion=${agentVersion/$'\r\n\t'}
          cd ${{ github.workspace }}/build/Linux
          docker-compose build build_deb
          docker-compose run -e AGENT_VERSION=$agentVersion build_deb
        shell: bash
        
      - name: Archive Package Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-folder-artifacts
          path: ${{ github.workspace }}/src/_build
          if-no-files-found: error

  run-artifactbuilder:
    needs: [ create-package-rpm, create-package-deb ]
    if: ${{ github.event.release }}
    name: Run ArtifactBuilder
    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download Agent Home Folders
        uses: actions/download-artifact@v2
        with:
          name: homefolders
          path: src/Agent 
      
      - name: Download _build Artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-folder-artifacts
          path: src/_build

      - name: Download NewRelic.NuGetHelper
        uses: actions/download-artifact@v2
        with:
          name: NewRelic.NuGetHelper
          path: build/NewRelic.NuGetHelper/bin
      
      - name: Download NewRelic.Agent.Extensions
        uses: actions/download-artifact@v2
        with:
          name: NewRelic.Agent.Extensions
          path: src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/bin/Release

      - name: Download NewRelic.OpenTracing.AmazonLambda.Tracer
        uses: actions/download-artifact@v2
        with:
          name: NewRelic.OpenTracing.AmazonLambda.Tracer
          path: src/AwsLambda/AwsLambdaOpenTracer/bin/Release/netstandard2.0-ILRepacked

      - name: Run ArtifactBuilder
        run: |
          ${{ github.workspace }}\build\package.ps1 -configuration Release -IncludeDownloadSite
        shell: powershell

      - name: Archive Deploy Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: deploy-artifacts
          path: |
            ${{ github.workspace }}\build\BuildArtifacts
            ${{ github.workspace }}\deploy
          if-no-files-found: error
