# This is a basic workflow to help you get started with Actions

name: featuretesting

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run-unbounded-tests:
    name: Run Unbounded Tests

    runs-on: windows-2019

    steps:
    - name: Install dependencies
      run: |
        Write-Host "Installing Msmq Features"
        Enable-WindowsOptionalFeature -Online -FeatureName MSMQ-Server -All
        Enable-WindowsOptionalFeature -Online -FeatureName MSMQ-HTTP -All
        Enable-WindowsOptionalFeature -Online -FeatureName MSMQ-Triggers -All
      shell: powershell
