# This is a basic workflow to help you get started with Actions

name: featuretesting

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run-unbounded-tests:
    name: Run Unbounded Tests

    runs-on: windows-2019

    steps:
    - name: Install dependencies
      run: |
        $registryRootPath = "HKCU:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols"
        $tls10 = "TLS 1.0"
        $tls11 = "TLS 1.1"
        $tls12 = "TLS 1.2"
        $client = "Client"
        $server = "Server"

        $registryPaths = @(
        "$registryRootPath\$tls10\$client",
        "$registryRootPath\$tls10\$server",
        "$registryRootPath\$tls11\$client",
        "$registryRootPath\$tls11\$server",
        "$registryRootPath\$tls12\$client",
        "$registryRootPath\$tls12\$server"
        )

        $name = "Enabled"
        $value = "1"

        foreach ($registryPath in $registryPaths) {
          if(!(Test-Path $registryPath)) {
            New-Item -Path $registryPath -Force | Out-Null
            New-ItemProperty -Path $registryPath -Name $name -Value $value -PropertyType DWORD -Force | Out-Null
          }
          else {
            New-ItemProperty -Path $registryPath -Name $name -Value $value -PropertyType DWORD -Force | Out-Null
          }
        }
      shell: powershell
