# This is a basic workflow to help you get started with Actions

name: featuretesting

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cancel:
    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Runs
      uses: rokroskar/workflow-run-cleanup-action
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  run-unbounded-tests:
    needs: [cancel]
    name: Run Unbounded Tests

    runs-on: windows-2019

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Install dependencies
      run: |
        Write-Host "Installing MSSQL CLI"
        cd ${{ github.workspace }}\build\Tools
        Start-Sleep 500
        ls
      shell: powershell
