# This is a basic workflow to help you get started with Actions

name: featuretesting

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch:
   

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  github-runid:
    name: Get the GitHub Workflow Run ID
    runs-on: ubuntu-latest
    steps:
      - name: Run ID
        run: |
          echo "${{ github.run_id }}"
        shell: bash
