# This is a basic workflow to help you get started with Actions

name: featuretesting

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run-unbounded-tests:
    name: Run Unbounded Tests

    runs-on: windows-2019

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Install dependencies
      run: |
        Write-Host "Installing MSSQL CLI"
        cd ${{ github.workspace }}\build\Tools
        ls
        
        Write-Host " "
        
        Write-Host "msiexec /i ${{ github.workspace }}\build\Tools\sqlncli.msi IACCEPTSQLNCLILICENSETERMS=YES /quiet /qn /norestart /L*V ${{ github.workspace }}\build\Tools\sqlncli.log"
        msiexec /i "${{ github.workspace }}\build\Tools\sqlncli.msi" IACCEPTSQLNCLILICENSETERMS=YES /quiet /qn /norestart /L*V "${{ github.workspace }}\build\Tools\sqlncli.log"
        Start-Sleep 15
        ls
        
        Write-Host " "
        
        Write-Host "${{ github.workspace }}\build\Tools\sqlncli.log"
        Get-Content "${{ github.workspace }}\build\Tools\sqlncli.log"
      shell: powershell
