# This is a basic workflow to help you get started with Actions

name: featuretesting

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  release:
    types: [ published ]

env:
  stuff: "nope"
   

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cancel-previous-workflow-runs:
    if: github.event_name == 'release' && startsWith( github.ref, 'refs/tags/v' )
    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  vars-linux:
    needs: cancel-previous-workflow-runs
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: set output
        run: |
          echo "::set-output name=action_fruit::strawberry"
          echo "woo=cool" >> $GITHUB_ENV
          echo "======================================"
          echo "$GITHUB_ENV"
          echo "======================================"
          cat "$GITHUB_ENV"
          echo "======================================"
        shell: bash
