name: start a release of aws

on:
  release:
    types: [ published ]

jobs:
  cancel-previous-workflow-runs: # github.ref == "refs/tags/<tag_name>"
    if: github.event_name == release && startsWith( github.ref, refs/tags/AwsLambdaOpenTracer_v )
    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  start-lambda-release:
    needs: cancel-previous-workflow-runs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
          
      - name: Create and push tag
        run: |
          echo "go go lambda"
