name: start a release of aws

on:
  workflow_dispatch:
    inputs:
      agent_version:
        description: 'AWS Version to deploy.'
        required: true

jobs:
  start-lambda-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.git.createTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: "AwsLambdaOpenTracer_v${{ github.event.inputs.agent_version }}",
              message: "stuff",
              object: "${{ github.sha }}",
              type: commit,
            });
