name: start a release of aws

on:
  workflow_dispatch:
    inputs:
      agent_version:
        description: 'AWS Version to deploy.'
        required: true

jobs:
  start-lambda-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
          
      - name: Create and push tag
        run: |
          git config --local user.email "noreply@newrelic.com"
          git config --local user.name "dotnetteam[bot]"
          git tag -a AwsLambdaOpenTracer_v${{ github.event.inputs.agent_version }} -m "AwsLambdaOpenTracer_v${{ github.event.inputs.agent_version }}"
          git push origin AwsLambdaOpenTracer_v${{ github.event.inputs.agent_version }}
