name: start a release of aws

on:
  workflow_dispatch:
    inputs:
      agent_version:
        description: 'AWS Version to deploy.'
        required: true

jobs:
  start-lambda-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Create tag
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/AwsLambdaOpenTracer_v${{ github.event.inputs.agent_version }}",
              sha: context.sha
            })
