name: New Relic Logging Extensions for .NET

on:
  pull_request:
    branches: [ master ]

jobs:

  build-test:

    runs-on: windows-2019

    env:
      artifact_staging_path: ${{ github.workspace }}\artifactstaging
      DOTNET_NOLOGO: true
      #<other env vars here>

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.1
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.200

    - name: Setup Artifact Staging
      run: New-Item -Path "${{ github.workspace }}" -Name "artifactstaging" -ItemType "directory"
      shell: powershell

    - name: Install SonarScanner
      run: dotnet tool install --global dotnet-sonarscanner --version 4.10.0
      shell: powershell

      - name: Setup Nuget
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NuGetAPIKey }}
          nuget-version: '5.x'

    - name: SonarScanner Begin
      run: dotnet-sonarscanner begin /k:"project-key" /o:"<organization>" /d:sonar.login="<token>"
      shell: powershell

    - name: Build
      run:  dotnet build NewRelic.LogEnrichers.sln --configuration Release
      shell: powershell

    - name: Test Serilog
      run:  dotnet test src/Serilog/NewRelic.LogEnrichers.Serilog.Tests --no-build --no-restore --configuration Release --logger trx
      shell: powershell

    - name: Test NLog
      run:  dotnet test src/NLog/NewRelic.LogEnrichers.NLog.Tests --no-build --no-restore --configuration Release --logger trx
      shell: powershell
    
    - name: Test Log4Net
      run:  dotnet test src/Log4Net/NewRelic.LogEnrichers.Log4Net.Tests --no-build --no-restore --configuration Release --logger trx
      shell: powershell

    - name: SonarScanner End
      run: dotnet-sonarscanner end /d:sonar.login="<token>"
      shell: powershell
      
    - name: Archive the artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact-${{ github.run_id }}
        path: ${{ env.solution_path }}

    - name: Copy Serilog Build Artifacts to Staging Location
      run: 
      shell: powershell

    - name: Copy NLog Build Artifacts to Staging Location
      run: 
      shell: powershell

    - name: Copy Log4Net Build Artifacts to Staging Location
      run: 
      shell: powershell

    - name: Publish to MyGet
      run: nuget push stuf and things
