name: .NET Agent Pull Request Builder

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build-test:

    runs-on: windows-2019

    env:
      solution_path: ${{ github.workspace }}\FullAgent.sln
      scripts_path: ${{ github.workspace }}\build\scripts
      tools_path: ${{ github.workspace }}\build\Tools
      
      DOTNET_NOLOGO: true
      #<other env vars here>

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.1
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.200

    - name: Install dependencies
      run: |
        Write-Host ${{ env.tools_path }}\nuget.exe restore ${{ env.solution_path }} -NoCache -Source `"https://www.nuget.org/api/v2`"
        ${{ env.tools_path }}\nuget.exe restore ${{ env.solution_path }} -NoCache -Source "https://www.nuget.org/api/v2"
      shell: powershell

    - name: Build
      run: |
        Write-Host "MSBuild.exe -m -p:Configuration=Release -p:AllowUnsafeBlocks=true ${{ env.solution_path }}"
        MSBuild.exe -m -p:Configuration=Release -p:AllowUnsafeBlocks=true ${{ env.solution_path }}
      shell: powershell

    - name: Archive the artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact-${{ github.run_id }}
        path: ${{ env.solution_path }}

    - name: Unit Tests
      run: |
        Write-Host ${{ env.scripts_path }}\DotNet-Agent-CI-UnitTests.ps1
        ${{ env.scripts_path }}\DotNet-Agent-CI-UnitTests.ps1
      shell: powershell
