name: .NET Agent Pull Request Builder

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:

  build-test:

    runs-on: windows-2019

    env:
      solution_path: ${{ github.workspace }}\FullAgent.sln
      nuget_path:  ${{ github.workspace }}\build\Tools\nuget.exe
      DOTNET_NOLOGO: true
      #<other env vars here>

    steps:
    - uses: actions/checkout@v2

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.1
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.200

    - name: Install dependencies
      run: |
        Write-Host ${{ env.nuget_path }} restore ${{ env.solution_path }} -NoCache -Source `"https://www.nuget.org/api/v2`"
        ${{ env.nuget_path }} restore ${{ env.solution_path }} -NoCache -Source "https://www.nuget.org/api/v2"

    - name: Build
      run: Write-Host "MSBuild.exe -m -p:Configuration=Release;AllowUnsafeBlocks=true ${{ env.solution_path }}"
      shell: powershell

    - name: Test
      run: Write-Host hello
      shell: powershell
